//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dziennik.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DziennikEntities : DbContext
    {
        public DziennikEntities()
            : base("name=DziennikEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Klasa> Klasy { get; set; }
        public virtual DbSet<Nauczyciel> Nauczyciele { get; set; }
        public virtual DbSet<Ocena> Oceny { get; set; }
        public virtual DbSet<Odpowiedz> Odpowiedzi { get; set; }
        public virtual DbSet<Ogloszenia> Ogloszenia { get; set; }
        public virtual DbSet<Osoba> Osoby { get; set; }
        public virtual DbSet<Przedmiot> Przedmioty { get; set; }
        public virtual DbSet<Pytanie> Pytania { get; set; }
        public virtual DbSet<Rodzic> Rodzice { get; set; }
        public virtual DbSet<Status> Statusy { get; set; }
        public virtual DbSet<Test> Testy { get; set; }
        public virtual DbSet<Uczen> Uczniowie { get; set; }
        public virtual DbSet<Wiadomosc> Wiadomosci { get; set; }
        public virtual DbSet<PrzedmiotyWKlasie> PrzedmiotyWKlasach { get; set; }
    }
}
