//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dziennik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nauczyciel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nauczyciel()
        {
            this.Klasas = new HashSet<Klasa>();
            this.Tests = new HashSet<Test>();
            this.Wiadomoscs = new HashSet<Wiadomosc>();
            this.PrzedmiotyWKlasies = new HashSet<PrzedmiotyWKlasie>();
        }
    
        public int id_nauczyciela { get; set; }
        public int id_osoby { get; set; }
        public int id_przedmiotu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Klasa> Klasas { get; set; }
        public virtual Osoba Osoba { get; set; }
        public virtual Przedmiot Przedmiot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test> Tests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wiadomosc> Wiadomoscs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrzedmiotyWKlasie> PrzedmiotyWKlasies { get; set; }
    }
}
