//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dziennik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odpowiedz
    {
        public int id_odpowiedzi { get; set; }
        public string tresc { get; set; }
        public int id_pytania { get; set; }
        public bool czyPoprawna { get; set; }
    
        public virtual Pytanie Pytanie { get; set; }
    }
}
