//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dziennik.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Ogloszenia
    {
        public int id_ogloszenia { get; set; }
        public string tresc { get; set; }
        [DisplayFormat(DataFormatString = "{0:d}")]
        public System.DateTime data_dodania { get; set; }
        public int id_statusu { get; set; }
        [DisplayFormat(DataFormatString = "{0:d}")]
        public System.DateTime data_waznosci { get; set; }
        public string tytul { get; set; }
        public Nullable<int> id_klasy { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual Klasa Klasa { get; set; }
    }
}
