//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dziennik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrzedmiotyWKlasie
    {
        public int id_przedmiotu_w_klasie { get; set; }
        public int id_przedmiotu { get; set; }
        public int id_klasy { get; set; }
        public int id_nauczyciela { get; set; }
    
        public virtual Klasa Klasa { get; set; }
        public virtual Przedmiot Przedmiot { get; set; }
        public virtual Nauczyciel Nauczyciel { get; set; }
    }
}
