//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dziennik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pytanie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pytanie()
        {
            this.Odpowiedzs = new HashSet<Odpowiedz>();
        }
    
        public int id_pytania { get; set; }
        public int id_testu { get; set; }
        public string tresc { get; set; }
        public int pkt_za_odpowiedz { get; set; }
    
        public virtual Test Test { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Odpowiedz> Odpowiedzs { get; set; }
    }
}
