//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dziennik.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Wiadomosc
    {
        public int id_wiadomosci { get; set; }
        public string tresc { get; set; }
        public int id_rodzica { get; set; }
        public int id_nauczyciela { get; set; }
        [DisplayFormat(DataFormatString = "{0:d}")]
        public System.DateTime data { get; set; }
        public string odpowiedz { get; set; }
        public string tytul { get; set; }
        public bool czyNauczyciel { get; set; }
        public bool czyRodzic { get; set; }
    
        public virtual Nauczyciel Nauczyciel { get; set; }
        public virtual Rodzic Rodzic { get; set; }
        public virtual Wiadomosc Wiadomosc1 { get; set; }
        public virtual Wiadomosc Wiadomosc2 { get; set; }
    }
}
